version: "3"
volumes:
  var:
  db:

services:
  app:
    image: vaem/asset-manager
    ports:
    - 5000:5000
    environment:
      MONGO_URL: mongodb://mongo:27017/asset-manager
      NODE_ENV: production
      SIGNATURE_SECRET: 'my signature secret'
      JWT_SECRET: 'my jwt secret'
      BASE: 'public base url'
    volumes:
      - var:/app/var

  encoder:
    image: vaem/encoder
    environment:
      ASSETMANAGER_URL: http://app:5000/

  mongo:
    image: mongo:4.2.0
    volumes:
      - db:/data/db
