volumes:
  data:

services:
  mongo:
    image: mongo:5.0
    ports:
      - "33206:27017"
    volumes:
      - data:/data/db

  subtitleedit:
    platform: linux/amd64
    image: vaem/subtitleedit-api
    environment:
      - API_KEY=vaem
    ports:
      - "26525:5000"
